name: MMP2.0-BO Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "30 1 * * 1-5"
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Using GitHub's checkout action

      - name: Set up Node.js
        uses: actions/setup-node@v2 # Using GitHub's setup-node action
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Archive test reports
        if: always() # Always run this step
        run: |
          tar -czf playwright-report.tar.gz playwright-report/
          mv playwright-report.tar.gz $GITHUB_WORKSPACE/playwright-report.tar.gz

      - name: Upload test reports
        if: always() # Always run this step
        uses: actions/upload-artifact@v2 # Using GitHub's upload-artifact action
        with:
          name: playwright-report
          path: $GITHUB_WORKSPACE/playwright-report.tar.gz
