name: MMP2.0-BO Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "30 1 * * 1-5"
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 3: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step 4: Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test

      # Step 5: Archive test reports
      - name: Archive test reports
        if: always() # Always run this step
        run: |
          tar -czf playwright-report.tar.gz playwright-report/
          mv playwright-report.tar.gz $GITHUB_WORKSPACE/playwright-report.tar.gz

      # Step 6: Upload test reports as artifact using REST API
      - name: Upload test reports
        if: always() # Always run this step
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/gzip" --data-binary @$GITHUB_WORKSPACE/playwright-report.tar.gz "https://api.github.com/repos/vanilla-8s/MMP2-BO-Automation/actions/artifacts?name=playwright-report"